name: Check

on:
push:
branches:
- main

jobs:
check-secret:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Check for SECRET
    run: |
      if grep -R "SECRET" . --exclude-dir=.github; then
        echo "Found SECRET in repository"
        exit 1
      else
        echo "No SECRET found"
      fi
```
